baseURL = "https://ydeepk.github.io/"
languageCode = "en-us"
title = "Break It Better."
theme = "DoIt"
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params.section]
dateFormat = "Jan 2, 2006"

[params]
  description = "QA Automation, Performance, Tech Notes"
  tagline = "Break It Better. Fix It Smarter."

  enableDarkMode = true
  enableReadingTime = true
  enableShareButtons = true
  enableBreadcrumb = true

  ShowReadingTime = true
  ShowPostNavLinks = true

  [params.author]
    name = "Deepak Yadav"
    email = "deepakyadav@example.com"
    link = "https://ydeepk.github.io"
    defaultImage = "/images/default-og.png"

[params.home]
  enable = true
  layout = "list"
  postsPerPage = 10

[params.search]
  enable = true
  engine = "fuse"

[params.analytics]
  googleAnalytics = "G-TJELDPQ9RY"

[params.comments]
  enable = true
  provider = "giscus"

[params.giscus]
  repo = "ydeepk/ydeepk.github.io"
  repoId = "MDEwOlJlcG9zaXRvcnk1NTEyMzcxMA=="
  category = "General"
  categoryId = "DIC_kwDOA0ke_s4Cy_o9"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"

[params.social]
  github = "https://github.com/ydeepk"
  instagram = "https://instagram.com/ydeepk"
  linkedin = "https://linkedin.com/in/ydeepk"
  youtube = "https://youtube.com/@yourchannel"

[params.footer]
  enable = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
name = "About"
url = "/about/"
weight = 5
