baseURL = "https://ydeepk.github.io/"
languageCode = 'en-us'
title = "Break It Better"
theme = "DoIt-main"
pagination.pagerSize = 10


[taxonomies]
  category = "categories"
  tag = "tags"


[params]

  [params.author]
    name = "Deepak Yadav"
    email = "deepakyadav@example.com"
    link = "https://ydeepk.github.io"

  description = "QA Automation, Performance, Tech Notes"
  tagline = "Break It Better. Fix It Smarter."
  ShowReadingTime = true
  ShowPostNavLinks = true
  showCodeCopyButtons = true


[params.search]
  enable = true
  engine = "fuse"


[params.analytics]
  googleAnalytics = "G-TJELDPQ9RY"  # replace with your GA4 ID


[params.comments]
  enable = true
  provider = "giscus"


[params.giscus]
  repo = "ydeepk/ydeepk.github.io"
  repoId = "MDEwOlJlcG9zaXRvcnk1NTEyMzcxMA=="
  category = "General"
  categoryId = "DIC_kwDOA0ke_s4Cy_o9"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"


[params.social]
  github = "https://github.com/ydeepk"
  instagram = "https://instagram.com/ydeepk"
  linkedin = "https://linkedin.com/in/ydeepk"
  youtube = "https://youtube.com/@yourchannel"


[params.footer]
  enable = true
  custom = ["footer/custom-footer"]


[params.assets]
customCSS = ["css/home.css", "css/post.css", "css/post-extras.css", "css/footer.css"]


[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
name = "About"
url = "/about/"
weight = 5

[[menu.main]]
name = "Tools"
url = "/tools/"
weight = 6

[[menu.main]]
name = "Newsletter"
url = "/newsletter/"
weight = 5