baseURL = "https://ydeepk.github.io/"
languageCode = 'en-us'
title = "Break It Better"
theme = "Doti"
pagination.pagerSize = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Deepak Yadav"
  description = "QA Automation, Performance, Tech Notes"
  tagline = "Break It Better. Fix It Smarter."
  ShowReadingTime = true
  ShowPostNavLinks = true
  showCodeCopyButtons = true

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "categories"
url = "/categories/"
weight = 3

[[menu.main]]
name = "tags"
url = "/tags/"
weight = 4

[[menu.main]]
name = "About me"
url = "/about-me/"
weight = 5